### ISSUE TITLE
Game crash when opening the game menu after received a new item

### ISSUE THREAD

**Issue by paleclerc** [denoflionsx/OotRandoCoop#6] opened 2018-07-31 01:20 UTC
Game crash when opening the game menu after received a new item BUT before a transition. If you trigger a game transition, the issue doesn't happen.

Version: v2.0.9
Repro rate: 100%

Step to reproduce:
1- Start the game with 2 player
2- Player A find a new item that appears in the game menu
3- Player B open it game menu (without a transition)
4- See the Player B crashing

Workaround:
The player B can reconnect and resynch manually (this will make the player B restart at the Kokiri village).

**Comment by denoflionsx** [comment] 2018-08-07 07:58
So after further consideration I'm at least 98% sure your crash is caused by not following the instructions for the Randomizer itself. Crashing in menus is a tale tell sign that you aren't using a compressed rom. Closing this issue.

**Closed by denoflionsx** 2018-08-07 07:58 UTC
Labels: invalid

**Comment by denoflionsx** [comment] 2018-08-08 02:09
You **must** use a compressed rom with emulators. The instructions for the Randomizer itself state such. The crash has nothing to do with co-op.

**Comment by paleclerc** [comment] 2018-08-14 12:25
I confirm that was the issue, sorry about that! It worked really well!
